# curl -v -F key1=value1 -F upload=@localfilename URL
POST URL
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="key1"

value1
--WebAppBoundary
Content-Disposition: form-data; name="upload"; filename="localfilename"

< localfilename
--WebAppBoundary--

###

## get
GET https://guba.eastmoney.com/default,1_1.html

> {%
    client.global.set("data", response.body);
    client.log(typeof response.body)
%}

### List
# curl -v -F url=https://guba.eastmoney.com/default,1_1.html -F data=@1.html http://127.0.0.1:8080/list
POST http://127.0.0.1:8080/list
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="url"

https://guba.eastmoney.com/default,1_1.html
--WebAppBoundary
Content-Disposition: form-data; name="data"; filename="1.html"

< ./1.html
--WebAppBoundary--