### Get
GET https://guba.eastmoney.com/default,1_1.html

> {%
    client.global.set("data", response.body);
    client.log(typeof response.body)
%}

### hello
GET {{host}}

### List
# curl -v -F url=https://guba.eastmoney.com/default,1_1.html -F data=@1.html http://list.yuanben.org/list
POST {{host}}/list
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="url"

https://guba.eastmoney.com/default,1_1.html
--WebAppBoundary
Content-Disposition: form-data; name="data"; filename="1.html"

< ./1.html
--WebAppBoundary--